// Initial issues shown the very first time someone opens the app
// (before they have created any localStorage data of their own).
// Each issue is a plain object - this is our "data model".

export const INITIAL_ISSUES = [
  {
    id: "1",
    title: "Water cooler not working",
    description: "The water cooler on the 2nd floor of Block B has stopped dispensing water.",
    location: "Block B, 2nd Floor",
    category: "Plumbing",
    priority: "High",
    status: "In Progress",
    image: "https://picsum.photos/seed/plumbing/200/200",
    createdAt: Date.now() - 1000 * 60 * 60 * 2,
    updatedAt: Date.now() - 1000 * 60 * 60 * 1,
  },
  {
    id: "2",
    title: "Street light not working",
    description: "The street light near the library entrance stays off at night.",
    location: "Main Road, Near Library",
    category: "Electrical",
    priority: "Medium",
    status: "Pending",
    image: "https://picsum.photos/seed/electrical/200/200",
    createdAt: Date.now() - 1000 * 60 * 60 * 5,
    updatedAt: Date.now() - 1000 * 60 * 60 * 5,
  },
  {
    id: "3",
    title: "Overflowing dustbin",
    description: "The dustbin near the canteen area is overflowing and needs to be emptied.",
    location: "Canteen Area",
    category: "Cleanliness",
    priority: "Low",
    status: "Resolved",
    image: "https://picsum.photos/seed/cleanliness/200/200",
    createdAt: Date.now() - 1000 * 60 * 60 * 24,
    updatedAt: Date.now() - 1000 * 60 * 60 * 20,
  },
  {
    id: "4",
    title: "Broken bench",
    description: "A wooden bench on the ground floor of Block A has a broken leg.",
    location: "Block A, Ground Floor",
    category: "Infrastructure",
    priority: "Medium",
    status: "Pending",
    image: "https://picsum.photos/seed/infrastructure/200/200",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
  {
    id: "5",
    title: "AC not cooling",
    description: "The air conditioner in Computer Lab 1 is running but not cooling the room.",
    location: "Computer Lab 1",
    category: "Electrical",
    priority: "High",
    status: "In Progress",
    image: "https://picsum.photos/seed/electrical/200/200",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  },
];
